apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-postgress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-ceph-block