apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
spec:
  selector:
    matchLabels:
      app: customer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: kkosugiredhat/customer-api:v3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-api-service
spec:
  type: NodePort
  ports:
    - name: "customer-api-port"
      protocol: "TCP"
      port: 8080
  selector:
    app: customer-api
